src/Entity/Livre.php
<?php

namespace App\Entity;

use App\Repository\LivreRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;

#[
    ORM\Entity(repositoryClass: LivreRepository::class)
]
class Livre
{
    #[
        ORM\Id,
        ORM\GeneratedValue,
        ORM\Column(type: "integer")
    ]
    private ?int $id = null;

    #[
        ORM\Column(type: "string", length: 255)
    ]
    private ?string $Titre = null;

    #[
        ORM\Column(type: "string", length: 255)
    ]
    private ?string $Auteur = null;

    #[
        ORM\Column(type: "string", length: 500, nullable: true)
    ]
    private ?string $Description = null;

    #[
        ORM\Column(type: "string", length: 500)
    ]
    private ?string $Date_de_Paruption = null;

    #[
        ORM\Column(type: "integer", nullable: true)
    ]
    private ?int $Date_Emprunt = null;

    #[
        ORM\Column(type: "string", length: 255, nullable: true)
    ]
    private ?string $ImageName = null;

    private ?File $ImageFile;

    #[
        ORM\Column(type: "datetime_immutable", nullable: true)
    ]
    private ?\DateTimeImmutable $updatedAt = null;

    #[
        ORM\Column(type: "string", length: 255, nullable: true)
    ]
    private ?string $Pages_Nombres = null;

    #[
        ORM\Column(type: "string", length: 255)
    ]
    private ?string $Categorie = null;

    #[
        ORM\Column(type: "boolean")
    ]
    private ?bool $Statut = null;

    #[
        ORM\Column(type: "integer")
    ]
    private ?int $ISBN_Nombre = null;


    #[
        ORM\ManyToOne(inversedBy: "livres", cascade: ["persist", "remove"])
    ]

    private ?Membres $ID_Emprunteur = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->Titre;
    }

    public function setTitre(string $Titre): static
    {
        $this->Titre = $Titre;

        return $this;
    }

    public function getAuteur(): ?string
    {
        return $this->Auteur;
    }

    public function setAuteur(string $Auteur): static
    {
        $this->Auteur = $Auteur;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(?string $Description): static
    {
        $this->Description = $Description;

        return $this;
    }

    public function getDateDeParuption(): ?int
    {
        return $this->Date_de_Paruption;
    }

    public function setDateDeParuption(int $timetamp): static
    {

        $this->Date_de_Paruption = $timetamp;

        return $this;
    }

    public function getDateEmprunt(): ?int
    {
        return $this->Date_Emprunt;
    }

    public function setDateEmprunt(?int $timestamp): self
    {
        $this->Date_Emprunt = $timestamp;

        return $this;
    }

    public function getImageName(): ?string
    {
        return $this->ImageName;
    }

    public function setImageName(?string $Image): static
    {
        $this->ImageName = $Image;

        return $this;
    }

    public function getImageFile(): ?File
    {
        return $this->ImageFile;
    }

    public function setImageFile(?File $ImageFile = null): void
    {
        $this->ImageFile = $ImageFile;

        if ($ImageFile instanceof UploadedFile) {
            $this->updatedAt = new \DateTimeImmutable();
        }
    }

    public function getPagesNombres(): ?string
    {
        return $this->Pages_Nombres;
    }

    public function setPagesNombres(?string $Pages_Nombres): static
    {
        $this->Pages_Nombres = $Pages_Nombres;

        return $this;
    }

    public function getCategorie(): ?string
    {
        return $this->Categorie;
    }

    public function setCategorie(string $Categorie): static
    {
        $this->Categorie = $Categorie;

        return $this;
    }

    public function isStatut(): ?bool
    {
        return $this->Statut;
    }

    public function setStatut(bool $Statut): static
    {
        $this->Statut = $Statut;

        return $this;
    }

    public function getISBNNombre(): ?int
    {
        return $this->ISBN_Nombre;
    }

    public function setISBNNombre(int $ISBN_Nombre): static
    {
        $this->ISBN_Nombre = $ISBN_Nombre;

        return $this;
    }


    public function getIDEmprunteur(): ?Membres
    {
        return $this->ID_Emprunteur;
    }

    public function setIDEmprunteur(?Membres $ID_Emprunteur): self
    {
        $this->ID_Emprunteur = $ID_Emprunteur;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updatedAt;
    }
}

src/Controller/HomeController.php
<?php

// src/Controller/HomeController.php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;

use Symfony\Component\Routing\Annotation\Route;
use App\Entity\Livre;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;

class HomeController extends AbstractController
{
    #[Route('/', name: "home_route")]
    public function index(EntityManagerInterface $em, PaginatorInterface $paginator, Request $request): Response
    {
        $queryBuilder = $em->getRepository(Livre::class)->createQueryBuilder('l');

        //Appliquez les filtres ici en fonction des paramètres de requête
        if ($request->query->get('author') && $request->query->get('author') != 'none') {
            $queryBuilder->andWhere('l.Auteur = :auteur')
                ->setParameter('auteur', $request->query->get('author'));
        }
        //Récupérez la liste complète des auteurs
        $auteurs = $em->getRepository(Livre::class)->createQueryBuilder('l')
            ->select('l.Auteur')
            ->distinct(true)
            ->getQuery()
            ->getResult();

        if ($request->query->get('category') && $request->query->get('category') != 'none') {
            $queryBuilder->andWhere('l.Categorie = :category')
                ->setParameter('category', $request->query->get('category'));
        }

        $categories = $em->getRepository(Livre::class)->createQueryBuilder('l')
            ->select('l.Categorie')
            ->distinct(true)
            ->getQuery()
            ->getResult();

        if ($request->query->get('date') && $request->query->get('date') != 'none') {
            $queryBuilder->andWhere('l.Date_de_Paruption = :date')
                ->setParameter('date', $request->query->get('date'));
        }

        $dates = $em->getRepository(Livre::class)->createQueryBuilder('l')
            ->select('l.Date_de_Paruption')
            ->distinct(true)
            ->getQuery()
            ->getResult();

        if ($request->query->get('titre') && $request->query->get('titre') != 'none') {
            $queryBuilder->andWhere('l.Titre = :titre')
                ->setParameter('titre', $request->query->get('titre'));
        }

        $titres = $em->getRepository(Livre::class)->createQueryBuilder('l')
            ->select('l.Titre')
            ->distinct(true)
            ->getQuery()
            ->getResult();




        $pagination = $paginator->paginate(
            $queryBuilder->getQuery(),
            $request->query->getInt('page', 1),
            3 // Nombre d'éléments par page
        );

        return $this->render('home/index.html.twig', [
            'livres' => $pagination,
            'auteurs' => $auteurs,
            'categories' => $categories,
            'dates' => $dates,
            'titres' => $titres,
        ]);
    }
}

templates/home/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Bienvenue sur la Bibliothèque
{% endblock %}

{% block body %}
	<img class="background" src="https://www.bnf.fr/sites/default/files/styles/header_big_height/public/2021-11/jardin_fm_automne.jpg" alt="Aleq">
	<div class="container mt-4 mb-4">
		<div class="container-fluid topkek">
			<div class="row">
				<div class="col-12 text-center">
					<div class="bg-custom rounded p-3" style="max-width: 50%; margin: auto;">
						<h1 class="text-grey">Bienvenue dans le hub</h1>
						<h4 class="text-yellow">Voici la liste des livres</h4>
					</div>
				</div>
			</div>
		</div>
		<div class="container mt-4">
			<div class="row">
				<div class="col-md-3">
					<form id="filterForm" method="get" action="{{ path('home_route') }}">
						<select class="form-select" name="author" id="authorTri" onchange="document.getElementById('filterForm').submit();">
							<option value="none" selected disabled hidden>-- Choisissez un Auteur --</option>
							{% for auteur in auteurs %}
								<option value="{{ auteur.Auteur }}">{{ auteur.Auteur }}</option>
							{% endfor %}
						</select>
					</div>
					<div class="col-md-3">
						<select class="form-select" name="category" id="categoryTri" onchange="document.getElementById('filterForm').submit();">
							<option value="none" selected disabled hidden>-- Choisissez une Catégorie --</option>
							{% for categorie in categories %}
								<option value="{{ categorie.Categorie }}">{{ categorie.Categorie }}</option>
							{% endfor %}
						</select>
					</div>
					<div class="col-md-3">
						<select class="form-select" name="date" id="dateTri" onchange="document.getElementById('filterForm').submit();">
							<option value="none" selected disabled hidden>-- Choisissez une Date de Parution --</option>
							{% for date in dates %}
								<option value="{{ date.Date_de_Paruption }}">{{ date.Date_de_Paruption ? date.Date_de_Paruption|date('d-m-Y') : 'Non spécifiée' }}</option>
							{% endfor %}
						</select>
					</div>
					<div class="col-md-3">
						<select class="form-select" name="titre" id="titreTri" onchange="document.getElementById('filterForm').submit();">
							<option value="none" selected disabled hidden>-- Choisissez un Titre --</option>
							{% for titre in titres %}
								<option value="{{ titre.Titre }}">{{ titre.Titre }}</option>
							{% endfor %}
						</select>
					</div>
					<div class="row mt-3">
						<div class="col text-center">
							<button type="button" id="resetFilter" class="btn btn-secondary btn-md">Reset Filters</button>
						</div>
					</div>
				</form>
			</div>

		</div>
		<br><br>
		<div class="row row-cols-1 row-cols-md-3">
			{% for livre in livres %}
				<div class="col mb-4 livre" data-auteur="{{ livre.auteur }}" data-categorie="{{ livre.categorie }}" data-date="{{ livre.datedeparuption }}" data-titre="{{ livre.titre }}">
					<div class="card bg-custom">
						<a href="{{ path('details_livre', {'id': livre.id}) }}" class="text-decoration-none text-dark d-block position-relative">
							{% if livre.ImageName is not null %}
								<img src="{{ asset('img/CouvertureLivres/' ~ livre.ImageName) }}" class="card-img-top" alt="{{ livre.titre }}" style="width: 100%; height: 100%;">
							{% endif %}
							<div class="overlay position-absolute top-0 start-0 w-100 h-100" style="background-color: rgba(204, 187, 241, 0); transition: background-color 0.3s ease-in-out;"></div>
							<div class="card-body">
								<h5 class="card-title text-center">
									{{ livre.titre }}
								</h5>
								<p class="card-text text-center">{{ livre.auteur }}</p>
								<p class="card-text">
									{% if livre.statut == 1 %}🔴 Emprunté
										{% else %}✅ Disponible
									{% endif %}
								</p>
							</div>
						</a>
					</div>
				</div>
			{% endfor %}
		</div>
	</div>


	{# Afficher la pagination #}
	{# <div class="pagination"> #}
		{{ knp_pagination_render(livres) }}
	{# </div> #}
{% endblock %}