src/Entity/Livre.php
<?php

namespace App\Entity;

use App\Repository\LivreRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;

#[
    ORM\Entity(repositoryClass: LivreRepository::class)
]
class Livre
{
    #[
        ORM\Id,
        ORM\GeneratedValue,
        ORM\Column(type: "integer")
    ]
    private ?int $id = null;

    #[
        ORM\Column(type: "string", length: 255)
    ]
    private ?string $Titre = null;

    #[
        ORM\Column(type: "string", length: 255)
    ]
    private ?string $Auteur = null;

    #[
        ORM\Column(type: "string", length: 500, nullable: true)
    ]
    private ?string $Description = null;

    #[
        ORM\Column(type: "string", length: 500)
    ]
    private ?string $Date_de_Paruption = null;

    #[
        ORM\Column(type: "integer", nullable: true)
    ]
    private ?int $Date_Emprunt = null;

    #[
        ORM\Column(type: "string", length: 255, nullable: true)
    ]
    private ?string $ImageName = null;

    private ?File $ImageFile;

    #[
        ORM\Column(type: "datetime_immutable", nullable: true)
    ]
    private ?\DateTimeImmutable $updatedAt = null;

    #[
        ORM\Column(type: "string", length: 255, nullable: true)
    ]
    private ?string $Pages_Nombres = null;

    #[
        ORM\Column(type: "string", length: 255)
    ]
    private ?string $Categorie = null;

    #[
        ORM\Column(type: "boolean")
    ]
    private ?bool $Statut = null;

    #[
        ORM\Column(type: "integer")
    ]
    private ?int $ISBN_Nombre = null;


    #[
        ORM\ManyToOne(inversedBy: "livres", cascade: ["persist", "remove"])
    ]

    private ?Membres $ID_Emprunteur = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->Titre;
    }

    public function setTitre(string $Titre): static
    {
        $this->Titre = $Titre;

        return $this;
    }

    public function getAuteur(): ?string
    {
        return $this->Auteur;
    }

    public function setAuteur(string $Auteur): static
    {
        $this->Auteur = $Auteur;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(?string $Description): static
    {
        $this->Description = $Description;

        return $this;
    }

    public function getDateDeParuption(): ?int
    {
        return $this->Date_de_Paruption;
    }

    public function setDateDeParuption(int $timetamp): static
    {

        $this->Date_de_Paruption = $timetamp;

        return $this;
    }

    public function getDateEmprunt(): ?int
    {
        return $this->Date_Emprunt;
    }

    public function setDateEmprunt(?int $timestamp): self
    {
        $this->Date_Emprunt = $timestamp;

        return $this;
    }

    public function getImageName(): ?string
    {
        return $this->ImageName;
    }

    public function setImageName(?string $Image): static
    {
        $this->ImageName = $Image;

        return $this;
    }

    public function getImageFile(): ?File
    {
        return $this->ImageFile;
    }

    public function setImageFile(?File $ImageFile = null): void
    {
        $this->ImageFile = $ImageFile;

        if ($ImageFile instanceof UploadedFile) {
            $this->updatedAt = new \DateTimeImmutable();
        }
    }

    public function getPagesNombres(): ?string
    {
        return $this->Pages_Nombres;
    }

    public function setPagesNombres(?string $Pages_Nombres): static
    {
        $this->Pages_Nombres = $Pages_Nombres;

        return $this;
    }

    public function getCategorie(): ?string
    {
        return $this->Categorie;
    }

    public function setCategorie(string $Categorie): static
    {
        $this->Categorie = $Categorie;

        return $this;
    }

    public function isStatut(): ?bool
    {
        return $this->Statut;
    }

    public function setStatut(bool $Statut): static
    {
        $this->Statut = $Statut;

        return $this;
    }

    public function getISBNNombre(): ?int
    {
        return $this->ISBN_Nombre;
    }

    public function setISBNNombre(int $ISBN_Nombre): static
    {
        $this->ISBN_Nombre = $ISBN_Nombre;

        return $this;
    }


    public function getIDEmprunteur(): ?Membres
    {
        return $this->ID_Emprunteur;
    }

    public function setIDEmprunteur(?Membres $ID_Emprunteur): self
    {
        $this->ID_Emprunteur = $ID_Emprunteur;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updatedAt;
    }
}

src/Form/LivreType.php
<?php
// LivreType.php

namespace App\Form;

use App\Entity\Livre;
use App\Entity\Membres;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use App\Form\DataTransformer\TimestampToDateTimeTransformer;

class LivreType extends AbstractType
{
    private $transformer;

    public function __construct(TimestampToDateTimeTransformer $transformer)
    {
        $this->transformer = $transformer;
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('Titre', TextType::class)
            ->add('Auteur', TextType::class)
            ->add('Description', TextareaType::class, [
                'required' => false,
            ])
            ->add('Date_de_Paruption', DateType::class, [
                'label' => 'Date de Parution',
                'widget' => 'single_text',
                'attr' => [
                    'placeholder' => 'Date de Parution',
                    'class' => 'form-control',
                ],
                'format' => 'yyyy-MM-dd', // Format de date en anglais
            ])
            ->add('Date_Emprunt', DateType::class, [
                'label' => 'Date Emprunt',
                'widget' => 'single_text',
                'attr' => [
                    'placeholder' => 'Date Emprunt',
                    'class' => 'form-control',
                ],
                'format' => 'yyyy-MM-dd', // Format de date en anglais
                'required' => false,
            ])
            ->add('ImageFile', FileType::class, [
                'required' => false,
            ])
            ->add('Pages_Nombres', TextType::class, [
                'required' => false,
            ])
            ->add('Categorie', ChoiceType::class, [
                'choices' => [
                    'Fantastique' => 'Fantastique',
                    'Poésie' => 'Poésie',
                    'Bande Déssinée' => 'Bande Déssinée',
                    'Chroniques' => 'Chroniques',
                    'Littérature jeunesse' => 'Littérature jeunesse',
                    'Science-fiction' => 'Science-fiction',
                    'Nouvelles' => 'Nouvelles',
                ],
            ])
            ->add('Statut', CheckboxType::class, [
                'required' => false,
            ])
            ->add('ISBN_Nombre', IntegerType::class)
            ->add('ID_Emprunteur', EntityType::class, [
                'class' => Membres::class,
                'choice_label' => 'Nom', // ou toute autre propriété que vous souhaitez afficher
                'required' => false, // Permettre la sélection d'aucun membre
            ]);

        $builder->get('Date_de_Paruption')
            ->addModelTransformer($this->transformer);

        $builder->get('Date_Emprunt')
            ->addModelTransformer($this->transformer);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Livre::class,
        ]);
    }
}

src/Controller/LivreController.php
<?php

// src/Controller/LivreController.php

namespace App\Controller;

use App\Form\LivreType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\Livre;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\File\UploadedFile;

class LivreController extends AbstractController
{
    #[Route('/livre/add', name: 'livres_add')]
    public function add(Request $request, EntityManagerInterface $entityManager): Response
    {
        $livre = new Livre();

        $form = $this->createForm(LivreType::class, $livre);
        $form->handleRequest($request);
        dump($livre);

        if ($form->isSubmitted() && $form->isValid()) {

            /** @var UploadedFile $ImageFile */
            $ImageFile = $form['ImageFile']->getData();

            if ($ImageFile) {
                $newImageName = $this->uploadImage($ImageFile);
                $livre->setImageName($newImageName);
            }

            $dateParutionTimestamp = $form['Date_de_Paruption']->getData();
            if ($dateParutionTimestamp instanceof \DateTimeInterface) {
                $livre->setDateDeParuption($dateParutionTimestamp->getTimestamp());
            }

            $dateEmpruntTimestamp = $form['Date_Emprunt']->getData();
            if ($dateEmpruntTimestamp instanceof \DateTimeInterface) {
                $livre->setDateEmprunt($dateEmpruntTimestamp->getTimestamp());
            } else {
                $livre->setDateEmprunt(null);
            }

            $entityManager->persist($livre);
            $entityManager->flush();

            return $this->redirectToRoute('home_route');
        }

        return $this->render('livre/index.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    private function uploadImage(UploadedFile $imageFile): string
    {
        $destination = $this->getParameter('kernel.project_dir') . '/public/img/CouvertureLivres';
        $originalFilename = pathinfo($imageFile->getClientOriginalName(), PATHINFO_FILENAME);
        $newFilename = $originalFilename . '-' . uniqid() . '.' . $imageFile->guessExtension();

        $imageFile->move($destination, $newFilename);

        return $newFilename;
    }


    #[Route('/livre/supprimer/{id}', name: 'supprimer_livre')]
    public function supprimerLivre(Livre $livre, EntityManagerInterface $entityManager): Response
    {
        $entityManager->remove($livre);
        $entityManager->flush();

        return $this->redirectToRoute('home_route');
    }
    #[Route('/livre/modifier/{id}', name: 'modifier_livre')]
    public function modifierLivre(Livre $livre, Request $request, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(LivreType::class, $livre);  // Utilisez LivreType ici

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $ImageFile = $form['ImageFile']->getData();

            if ($ImageFile) {
                $newImageName = $this->uploadImage($ImageFile);
                $livre->setImageName($newImageName);
            }

            $dateParutionTimestamp = $form['Date_de_Paruption']->getData();
            if ($dateParutionTimestamp instanceof \DateTimeInterface) {
                $livre->setDateDeParuption($dateParutionTimestamp->getTimestamp());
            }

            $dateEmpruntTimestamp = $form['Date_Emprunt']->getData();
            if ($dateEmpruntTimestamp instanceof \DateTimeInterface) {
                $livre->setDateEmprunt($dateEmpruntTimestamp->getTimestamp());
            }

            $entityManager->flush();

            return $this->redirectToRoute('details_livre', ['id' => $livre->getId()]);
        }

        return $this->render('livre/modifier.html.twig', [
            'form' => $form->createView(),
            'livre' => $livre,
        ]);
    }
    #[Route('/livre/{id}', name: 'details_livre')]
    public function detailsLivre(EntityManagerInterface $em, Livre $livre): Response
    {
        return $this->render('livre/details.html.twig', [
            'livre' => $livre,
        ]);


    }
}

templates/livre/details.html.twig
{% extends 'base.html.twig' %}

{% block title %}Détails du Livre
{% endblock %}

{% block body %}
	<img class="background" src="https://www.bnf.fr/sites/default/files/styles/header_big_height/public/2021-11/jardin_fm_automne.jpg" alt="Aleq">
	<div class="container mt-4 mb-4">
		<div class="card bg-custom">
			<div class="card-body">
				<h1 class="card-title text-center">{{ livre.titre }}</h1>
				{% if livre.ImageName is not null %}
					<img src="{{ asset('img/CouvertureLivres/' ~ livre.ImageName) }}" alt="{{ livre.titre }}" class="img-fluid mb-3" style="max-width: 25%; max-height: 25%;">
				{% endif %}
				<p class="card-text">Auteur :
					{{ livre.auteur }}</p>
				<p class="card-text">Description :
					{{ livre.description }}</p>
				<p class="card-text">Date de Parution :
					{{ livre.DatedeParuption ? livre.DatedeParuption|date('d-m-Y') : 'Non spécifiée' }}</p>
				<p class="card-text">Nombre de Pages :
					{{ livre.PagesNombres }}</p>
				<p class="card-text">Catégorie :
					{{ livre.categorie }}</p>
				<p class="card-text">Statut :
					{{ livre.Statut ? '🔴 Emprunté' : '✅ Disponible' }}</p>
				{% if livre.Statut %}
					<p class="card-text">A été emprunté le
						{{ livre.DateEmprunt|date('Y-m-d') }}</p>
				{% endif %}
				<p class="card-text">ISBN :
					{{ livre.ISBNNombre }}</p>

				<form method="post" action="{{ path('supprimer_livre', {'id': livre.id}) }}" onsubmit="return confirm('Voulez-vous vraiment supprimer ce livre ?');">
					<button type="submit" class="btn btn-danger">Supprimer le livre</button>
					<a href="{{ path('home_route') }}" class="btn btn-secondary">Retour à la liste des livres</a>
					<a href="{{ path('modifier_livre', {'id': livre.id}) }}" class="btn btn-primary">Modifier le livre</a>
				</form>
			</div>
		</div>
	</div>
{% endblock %}

templates/livre/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter un Livre
{% endblock %}

{% block body %}
	<img class="background" src="https://www.bnf.fr/sites/default/files/styles/header_big_height/public/2021-11/jardin_fm_automne.jpg" alt="Aleq">
	<div class="container">
		<h1 class="mt-4 mb-4 text-black alert alert-info text-center">Salutations Employé 427 ! ✅</h1>
		<div class="alert alert-info">
			<h2>Veuillez vérifier ces paramètres avant de créer une entrée dans la BDD :</h2>
			<ul>
				<li>Aucune case ne doit être vide de données.</li>
				<li>Le fichier de l'image doit être dans ces formats : 'jpg', 'png', 'jpeg', 'gif', 'webp'</li>
			</ul>
		</div>

		<h1 class="mt-4 mb-4 text-black alert alert-info text-center">Ajouter un Livre</h1>

		{{ form_start(form, {'attr': {'class': 'needs-validation', 'novalidate': 'novalidate'}}) }}

		<div class="row alert alert-info">
			<div class="col-md-6 mb-3 text-black text-center">
				{{ form_row(form.Titre, {'attr': {'class': 'form-control', 'placeholder': 'Titre'}}) }}
			</div>
			<div class="col-md-6 mb-3 text-black text-center">
				{{ form_row(form.Auteur, {'attr': {'class': 'form-control', 'placeholder': 'Auteur'}}) }}
			</div>
			<div class="col-md-6 mb-3 text-black text-center">
				{{ form_row(form.Description, {'attr': {'class': 'form-control', 'placeholder': 'Description'}}) }}
			</div>
			<div class="col-md-6 mb-3 text-black text-center">
				{{ form_row(form.Date_de_Paruption, {'attr': {'class': 'form-control', 'placeholder': 'Date de Parution'}}) }}
			</div>
			<div class="col-md-6 mb-3 text-black text-center">
				{{ form_row(form.ImageFile, {'attr': {'class': 'form-control', 'placeholder': 'Image'}}) }}
			</div>
			<div class="col-md-6 mb-3 text-black text-center">
				{{ form_row(form.Pages_Nombres, {'attr': {'class': 'form-control', 'placeholder': 'Pages'}}) }}
			</div>
			<div class="col-md-6 mb-3 text-black text-center">
				{{ form_row(form.Categorie, {'attr': {'class': 'form-control', 'placeholder': 'Catégorie'}}) }}
			</div>
			<div class="col-md-6 mb-3 text-black text-center">
				{{ form_row(form.Statut, {'attr': {'class': 'form-check-input'}}) }}
			</div>
			<div class="col-md-6 mb-3 text-black text-center">
				{{ form_row(form.ISBN_Nombre, {'attr': {'class': 'form-control', 'placeholder': 'ISBN'}}) }}
			</div>
			<div class="col-md-6 mb-3 text-black text-center">
				{{ form_row(form.Date_Emprunt, {'attr': {'class': 'form-control', 'placeholder': 'Date Emprunt'}}) }}
			</div>
			<div class="col-md-6 mb-3 text-black text-center">
				{{ form_row(form.ID_Emprunteur, {'attr': {'class': 'form-control', 'placeholder': "Nom de l'emprunteur"}}) }}
			</div>
		</div>

		{# Ajout de la condition pour afficher l'image si elle existe #}
		{% if form.vars.value.ImageName is not null %}
			<img src="{{ asset('img/CouvertureLivres/' ~ form.vars.value.ImageName) }}" alt="Image du livre" class="img-fluid mb-3">
		{% endif %}

		<button type="submit" class="btn btn-primary">Ajouter</button>
		{{ form_end(form) }}

		<br><br>

		{% if form_errors(form) %}
			<div class="alert alert-danger mt-3">
				{{ form_errors(form) }}
			</div>
		{% endif %}
	</div>
{% endblock %}

templates/livre/modifier.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier les informations du livre
{% endblock %}

{% block body %}
	<img class="background" src="https://www.bnf.fr/sites/default/files/styles/header_big_height/public/2021-11/jardin_fm_automne.jpg" alt="Aleq">
	
	<div class="container mt-4">
	<h1 class="row alert alert-info">Modifier le Livre</h1>
		{{ form_start(form) }}
		<div class="row">
			<div class="col-md-6 my-5">
				<div class="mb-3 text-white">
					{{ form_row(form.Titre, {'attr': {'class': 'form-control', 'placeholder': 'Titre'}}) }}
				</div>
				<div class="mb-3 text-white">
					{{ form_row(form.Auteur, {'attr': {'class': 'form-control', 'placeholder': 'Auteur'}}) }}
				</div>
				<div class="mb-3 text-white">
					{{ form_row(form.Description, {'attr': {'class': 'form-control', 'placeholder': 'Description'}}) }}
				</div>
				<div class="mb-3 text-white">
					{{ form_row(form.Date_de_Paruption, {'attr': {'class': 'form-control', 'placeholder': 'Date de Parution'}}) }}
				</div>
				{% if livre.ImageName is not null %}
					<img src="{{ asset('img/CouvertureLivres/' ~ livre.ImageName) }}" alt="{{ livre.Titre }}" style="max-width: 100px; max-height: 100px;" class="mb-3">
				{% endif %}
				<div class="mb-3 text-white">
					{{ form_row(form.ImageFile, {'attr': {'class': 'form-control', 'placeholder': 'Image'}}) }}
				</div>
			</div>
			<div class="col-md-6 my-5">
				<div class="mb-3 text-white">
					{{ form_row(form.Pages_Nombres, {'attr': {'class': 'form-control', 'placeholder': 'Pages'}}) }}
				</div>
				<div class="mb-3 text-white">
					{{ form_row(form.Categorie, {'attr': {'class': 'form-control', 'placeholder': 'Catégorie'}}) }}
				</div>
				<div class="mb-3 form-check text-white">
					{{ form_row(form.Statut, {'attr': {'class': 'form-check-input'}}) }}
				</div>
				<div class="mb-3 text-white">
					{{ form_row(form.Date_Emprunt, {'attr': {'class': 'form-control', 'placeholder': 'Date Emprunt'}}) }}
				</div>
				<div class="mb-3 text-white">
					{{ form_row(form.ID_Emprunteur, {'attr': {'class': 'form-control', 'placeholder': "Nom de l'emprunteur"}}) }}
				</div>
				<div class="mb-3 text-white">
					{{ form_row(form.ISBN_Nombre, {'attr': {'class': 'form-control', 'placeholder': 'ISBN'}}) }}
				</div>
			</div>
		</div>

		<div class="my-5">
			<a href="{{ path('details_livre', {'id': livre.id}) }}" class="btn btn-secondary">Retour aux détails</a>
			<button type="submit" class="btn btn-primary">Modifier le livre</button>
		</div>

		{{ form_end(form) }}
	</div>
{% endblock %}